### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by DayOfThePenguin** [klannon/deep_learning#1]
As of now, we are getting an UnboundLocalError that 'nrows' was referenced before assignment in the constructor for _Physics

**Comment by mdkdrnevich** [comment]
The way I changed the code nrows should either be defined or raise an exception (in the case that the file's name isn't HIGGS or SUSY), so if you didn't get an exception that is unusual. I did not find any errors when I ran the latest update of the code. Do you have more details on the traceback?

**Comment by DayOfThePenguin** [comment]
The problem is actually that pylearn2 was using a different version of physics.py than the one in our repository.  It was using the copy in /afs/.../pylearn2/pylearn2/datasets/ that I modified when working on making the code in https://github.com/uci-igb/higgs-susy run.  That's why I made the second suggestion that we change the imports so whichever version of the code we happen to be running will work irrespective of which physics.py is in /afs/.../pylearn2/pylearn2/datasets/
