### ISSUE TITLE
Using the physics.py file in the repository instead of from pylearn2/pylearn2/datasets/

### ISSUE THREAD

**Issue by DayOfThePenguin** [klannon/deep_learning#2]
It would be nice if we forced our scripts to use the version of physics.py that is in the repository instead of whatever version is sitting in our pylearn2/pylearn2/datasets/ folder.  All I would have to do is change the way the PHYSICS class is imported, and if no one is averse to my changing it, I will.

**Comment by mdkdrnevich** [comment]
I would appreciate that as well.

**Comment by DayOfThePenguin** [comment]
Done
