### ISSUE TITLE
Add OSU Data

### ISSUE THREAD

**Issue by klannon** [klannon/deep_learning#3]
Modify csvData.py and/or physics.py to read in the OSU datasets which can be found here: 
https://www.dropbox.com/sh/w7wm61ogs2zmzm8/AAD3ZGYug96Il9-66VC5slnha?dl=0

We want to read in the "test" and "train" txt files, in particular for the "3v" case (although being able to read in the others would be good.

**Comment by mdkdrnevich** [comment]
I have this finished, but is there any information you want printed to stdout during the process? Currently there is no output while reading the data. I will commit and push the current changes, but I'll wait to close the issue.
