### ISSUE TITLE
Create a training script that is as close to OSU/torch training as possible

### ISSUE THREAD

**Issue by klannon** [klannon/deep_learning#4]
We want to replicate the OSU network configuration and training here:
https://www.dropbox.com/s/4g3nwyy02s8lmvn/run_3v.lua?dl=0

This implies changing the network structure.  The following items should be changed for the network:
- Number of hidden units per layer should be reduced from 300 to 100
- We should look at changing the output layer from Sigmoid to Softmax
- We might consider changing the hidden layers from Tanh to RectifiedLinear.  This one I'm less sure about since I have little experience with rectified linear units and I'm not sure how they'll work.

We should also try to match the OSU training configuration.  They _are_ using SGD (I was wrong about this) but we should try their batch size, learning rate, etc.  We should also remove dropout, and possibly weight decay at the start.  Note: removing dropout involves changing the "cost" from the dropout one fo the MLP "default" one.  Also, it would be good to verify whether the "default" cost function in pylearn2 matches the actual cost that OSU is using in Torch.  If not, we should try to figure out how to match this as well.

**Comment by DayOfThePenguin** [comment]
I have almost gotten it, but the problem is that the output of the code from the paper was a 1-D array but the output from the OSU code was 2-D (as I understand it).  Here's the traceback I'm getting:

```
Data loaded: train
Data loaded: valid
Data loaded: test
15
/afs/crc.nd.edu/user/c/cdablain/pylearn2/pylearn2/train.py:85: UserWarning: dataset has no yaml src, model won't know what data it was trained on
  "data it was trained on")
Using=gpu
Writing to /scratch365/cdablain/dnn/deep-learning/osu/run_3v.log
Writing to /scratch365/cdablain/dnn/deep-learning/osu/run_3v.pkl
Traceback (most recent call last):
  File "run_3v.py", line 130, in <module>
    train(mytrain)
  File "run_3v.py", line 126, in train
    mytrain.main_loop()
  File "/afs/crc.nd.edu/user/c/cdablain/pylearn2/pylearn2/train.py", line 220, in main_loop
    rval = self.algorithm.train(dataset=self.dataset)
  File "/afs/crc.nd.edu/user/c/cdablain/pylearn2/pylearn2/training_algorithms/sgd.py", line 452, in train
    for batch in iterator:
  File "/afs/crc.nd.edu/user/c/cdablain/pylearn2/pylearn2/utils/iteration.py", line 984, in next
    rval = self._fallback_next(next_index)
  File "/afs/crc.nd.edu/user/c/cdablain/pylearn2/pylearn2/utils/iteration.py", line 1002, in _fallback_next
    for data, fn in safe_izip(self._raw_data, self._convert)
  File "/afs/crc.nd.edu/user/c/cdablain/pylearn2/pylearn2/utils/iteration.py", line 1002, in <genexpr>
    for data, fn in safe_izip(self._raw_data, self._convert)
  File "/afs/crc.nd.edu/user/c/cdablain/pylearn2/pylearn2/utils/iteration.py", line 952, in <lambda>
    dspace.np_format_as(batch, sp))
  File "/afs/crc.nd.edu/user/c/cdablain/pylearn2/pylearn2/space/__init__.py", line 486, in np_format_as
    space=space)
  File "/afs/crc.nd.edu/user/c/cdablain/pylearn2/pylearn2/space/__init__.py", line 544, in _format_as
    self._check_sizes(space)
  File "/afs/crc.nd.edu/user/c/cdablain/pylearn2/pylearn2/space/__init__.py", line 500, in _check_sizes
    str(other_dimension))
ValueError: VectorSpace(dim=1, dtype=float32) with total dimension 1 can't format a batch into VectorSpace(dim=2, dtype=float32)because its total dimension is 2
```

**Comment by klannon** [comment]
So, I don't know if this is something you've already done, but I've just pushed a version of run_3v.py that runs without crashing that has a softmax output layer after a collection of tanh layers.  This at least doesn't crash.  It's built on top of the changes that @mdkdrnevich included for adapting the outputs to be 2D.  However, when I put this in, I lose all the monitoring output.  I think that's because the monitoring is somehow implemented in the actual output layer and it seems like Softmax doesn't implement anything.  (Maybe?  I haven't really had a chance to dig into it.)  Can you guys play with this and see what you can find?

**Comment by mdkdrnevich** [comment]
I implemented dataset monitoring identical to that of the UCI code by adding an argument to the algorithm.SGD parameter.

**Comment by mdkdrnevich** [comment]
As far as I am aware, we had not tried what you were able to do by making the other layers tanh functions, and it's nice to see the model working! However, OSU seems to be using linear layers, so I assume we need to try and modify it to work for those? This does indicate that our error is in our lack of understanding in implementing a linear layer though. This is curious because tanh layers are sub-classes of the linear class, so there may be some hints in the tanh code to show us what we're missing (might be a good place to start looking, or may be totally wrong).

**Comment by mdkdrnevich** [comment]
So, I went to see if the default cost function for our model matched what OSU is using, but all the documentation says is it will call get_default_cost() which returns the default cost function for the model, yet the model's documentation has no indication of what its default cost function is. Is it fair to assume we are using the same function, or should we explicitly make one?

**Comment by klannon** [comment]
I think there are enough knobs and levers to understand that for the 
moment we can assume that since neither we nor OSU is attempting to do 
something "special" with the costs, that the default one we get is the 
same or at least not significantly different from OSU's.
